import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Eye, EyeOff, Zap, CheckCircle } from 'lucide-react';
import { z } from 'zod';

const passwordSchema = z.object({
  password: z.string()
    .min(8, 'Senha deve ter no mínimo 8 caracteres')
    .max(72, 'Senha deve ter no máximo 72 caracteres'),
  confirmPassword: z.string(),
}).refine((data) => data.password === data.confirmPassword, {
  message: 'As senhas não coincidem',
  path: ['confirmPassword'],
});

const ResetPassword = () => {
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [isRecovery, setIsRecovery] = useState(false);

  const navigate = useNavigate();

  const [checking, setChecking] = useState(true);

  useEffect(() => {
    let cancelled = false;

    const markRecoveryReady = () => {
      if (cancelled) return;
      setIsRecovery(true);
      setChecking(false);
      window.history.replaceState({}, document.title, window.location.pathname);
    };

    const finishInvalid = () => {
      if (cancelled) return;
      setIsRecovery(false);
      setChecking(false);
    };

    const waitForSession = async (timeoutMs = 4000) => {
      const startedAt = Date.now();
      while (!cancelled && Date.now() - startedAt < timeoutMs) {
        const { data } = await supabase.auth.getSession();
        if (data.session?.user) return true;
        await new Promise((resolve) => setTimeout(resolve, 250));
      }
      return false;
    };

    // Listen for auth state changes (PASSWORD_RECOVERY fires after hash/code is processed)
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event) => {
      if (event === 'PASSWORD_RECOVERY' || event === 'SIGNED_IN') {
        markRecoveryReady();
      }
    });

    const init = async () => {
      // Check for error in URL (expired/invalid link returned by Supabase)
      const hashParams = new URLSearchParams(window.location.hash.substring(1));
      const queryParams = new URLSearchParams(window.location.search);
      const errorCode = hashParams.get('error') || queryParams.get('error');

      if (errorCode) {
        finishInvalid();
        return;
      }

      // Direct app link generated by our backend: /reset-password?token_hash=...&type=recovery
      const tokenHash = queryParams.get('token_hash');
      const queryType = queryParams.get('type');
      if (tokenHash && queryType === 'recovery') {
        const { error } = await supabase.auth.verifyOtp({
          token_hash: tokenHash,
          type: 'recovery',
        });

        if (!error || await waitForSession(1500)) markRecoveryReady();
        else finishInvalid();
        return;
      }

      // Legacy hash flow: #access_token=...&type=recovery
      if (hashParams.get('type') === 'recovery') {
        markRecoveryReady();
        return;
      }

      // PKCE flow: ?code=...
      const code = queryParams.get('code');
      if (code) {
        if (await waitForSession(1000)) {
          markRecoveryReady();
          return;
        }

        const { error } = await supabase.auth.exchangeCodeForSession(code);
        if (!error || await waitForSession(1500)) markRecoveryReady();
        else finishInvalid();
        return;
      }

      // Fallback: maybe session is still being restored from a prior redirect/hash cleanup.
      if (await waitForSession()) markRecoveryReady();
      else finishInvalid();
    };

    init();

    return () => {
      cancelled = true;
      subscription.unsubscribe();
    };
  }, []);

  if (checking) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center">
            <CardTitle>Validando link...</CardTitle>
          </CardHeader>
        </Card>
      </div>
    );
  }

  const handleResetPassword = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const result = passwordSchema.safeParse({ password, confirmPassword });
      if (!result.success) {
        throw new Error(result.error.errors[0].message);
      }

      const { error } = await supabase.auth.updateUser({ password });

      if (error) throw error;

      setSuccess(true);
      toast.success('Senha redefinida!', {
        description: 'Sua senha foi alterada com sucesso.',
      });

      setTimeout(() => navigate('/'), 2000);
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Erro ao redefinir senha';
      toast.error('Erro ao redefinir senha', {
        description: message,
      });
    } finally {
      setLoading(false);
    }
  };

  if (!isRecovery) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center">
            <CardTitle>Link inválido</CardTitle>
            <CardDescription>
              Este link de redefinição de senha é inválido ou expirou.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button className="w-full" onClick={() => navigate('/auth')}>
              Voltar para login
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (success) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center">
            <CheckCircle className="h-12 w-12 text-green-500 mx-auto mb-4" />
            <CardTitle>Senha redefinida!</CardTitle>
            <CardDescription>
              Redirecionando para o sistema...
            </CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-background p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <div className="relative">
              <Zap className="h-8 w-8 text-primary animate-pulse" />
              <div className="absolute inset-0 bg-primary/20 rounded-full blur-xl" />
            </div>
            <span className="text-3xl font-bold bg-gradient-to-r from-amber-500 via-orange-500 to-amber-600 bg-clip-text text-transparent">
              SunFlow
            </span>
          </div>
          <CardTitle>Redefinir Senha</CardTitle>
          <CardDescription>
            Digite sua nova senha abaixo.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleResetPassword} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="new-password">Nova Senha</Label>
              <div className="relative">
                <Input
                  id="new-password"
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                  minLength={8}
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="absolute right-0 top-0 h-full px-3"
                  onClick={() => setShowPassword(!showPassword)}
                >
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </Button>
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="confirm-password">Confirmar Nova Senha</Label>
              <Input
                id="confirm-password"
                type={showPassword ? 'text' : 'password'}
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
                minLength={8}
              />
            </div>
            <Button type="submit" className="w-full" disabled={loading}>
              {loading ? 'Redefinindo...' : 'Redefinir Senha'}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
};

export default ResetPassword;
